#!/bin/sh

#  antimony 
#
#  A simple script that will generate 'ttf', 'eot', and 'woff'
#  font formats suitable for displaying webfonts. 
#
#  I use it in conjunction with Glyphs Mini, which exports an 
#  'otf' font format, to create icon sets.
#
#  Named for Antimony (Sb), Atomic Number 51, a hardening
#  element added to lead type to create sharp edges.
#

arg_path=`dirname $1`
arg_name=`basename $1 .otf`
font_ttf="$arg_name.ttf"
font_eot="$arg_name.eot"
font_woff="$arg_name.woff"


#######
# Setup 

NORMAL=$(tput sgr0)
UNDERLINE=$(tput smul)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

stage () {
    printf "${UNDERLINE}$1${NORMAL}\n"
}

task () {
    printf "    $1...\n"
}

complete () {
    printf "    ${GREEN}Done${NORMAL}\n\n"
}

error () {
    printf "${RED}${UNDERLINE}Error:${NORMAL} $1\n\n"
    exit 1
}


###########
# Scripting
stage "Building .ttf, .woff, .eot"
task "Making .ttf"
fontforge -lang=ff -c "Open('$1');Generate('$1':r+'.ttf');Quit(0);" > /dev/null 2>&1

complete

task "Making .eot"
ttf2eot $arg_path/$font_ttf > $arg_path/$font_eot 2>&1
complete

task "Making .woff"
sfnt2woff $1 > $arg_path/$font_woff 2>&1
complete

exit 0
