#!/bin/sh
#
# bash_text
#
# a little text formatting library.

# {
NORMAL=$(tput sgr0)
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

indent () {
    i=$1 
    while [ $i -gt 0 ]
    do
        printf "    "
    done
}
title () {
    printf "${BOLD}$1${NORMAL}\n"
}

subtitle () {
    printf "${UNDERLINE}$1${NORMAL}\n"
}

task () {
    indent 1
    printf "$1...\n"
}

complete () {
    indent 1
    printf "${GREEN}Done.${NORMAL}\n\n"
}

error () {
    printf "${RED}${UNDERLINE}Error:${NORMAL} $1\n\n"
    exit 1
}
# }
